### ISSUE TITLE
starting Kubelet

### ISSUE THREAD

**Issue by jibanes** [afbjorklund/buildroot4kubernetes#20]
* Is the best way to start kubernetes to run /etc/kubernetes/flannel.sh ?

**Comment by afbjorklund** [comment]
I added that little shell script because I always forget the CIDR parameter. (`--pod-network-cidr`)

Otherwise, it is https://github.com/flannel-io/flannel/blob/master/Documentation/kubernetes.md

----

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#initializing-your-control-plane-node

```
kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
```

**Comment by jibanes** [comment]
Thank you!
